version: "3.9"
services:
    weather:
        image: gimmitest/weather-img
        build:
            context: .
            dockerfile: Dockerfile
            args:
                DEFAULT_PORT: 3000
        container_name: weather
        ports:
            - 3000:3000
        environment:
            PORT: 3000
