apiVersion: v1
kind: Service
metadata:
    name: weather-service
spec:
    selector:
        app: node-backend
    ports:
        - port: 3000
          targetPort: 3000
          protocol: TCP
    type: NodePort
